package com.nik.domain;

public enum NotificationType {
    DUE_DATE_ALERT,
    BOOK_REMINDER,
    NEW_ARRIVAL,
    RECOMMENDATION,
    MARKETING,
    RESERVATION_AVAILABLE,
    RESERVATION_CREATED,
    RESERVATION_CANCELLED,
    RESERVATION_EXPIRED,
    RESERVATION_FULFILLED,
    SUBSCRIPTION_EXPIRING,
    FINE_NOTIFICATION,
    BOOK_RETURNED,
    PAYMENT_FAILED,
    SYSTEM_NOTIFICATION
}


